[project]
name = "llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "feedparser>=6.0.14",
    "langchain>=1.4.1",
    "langchain-core>=1.6.3",
    "langchain-google-genai>=4.4.0",
    "langchain-openai>=1.6.2",
    "trafilatura>=2.2.0",
]
